# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GR', 'Green'), ('BL', 'Blue'), ('SV', 'Silver'), ('RD', 'Red'), ('OR', 'Orange'), ('YL', 'Yellow')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.Line')),
            ],
        ),
    ]
