# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0003_station_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
