# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0005_auto_20170916_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='code2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transit.Station'),
        ),
        migrations.AddField(
            model_name='station',
            name='line2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_line', to='transit.Line'),
        ),
        migrations.AddField(
            model_name='station',
            name='line3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_line', to='transit.Line'),
        ),
        migrations.AlterField(
            model_name='station',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_line', to='transit.Line'),
        ),
    ]
